
require('./assets/GoToScene');
require('./assets/Script/GrayEffectScene/GrayEffectScene');
require('./assets/Script/MosaicEffectScene/MosaicEffectScene');
require('./assets/Script/ccutils/multiresolution/ContentAdapter');
require('./assets/Script/waterEffectScene/touch');
require('./assets/Script/waterEffectScene/wave');
require('./assets/shaderScene/BrightSaturaContrastTest/BrightSaturaContrastAssembler/BrightSaturaContrastAssembler');
require('./assets/shaderScene/BrightSaturaContrastTest/BrightSaturaContrastAssembler/BrightSaturaContrastAssemblerSprite');
require('./assets/shaderScene/BrightSaturaContrastTest/BrightSaturaContrastTest');
require('./assets/shaderScene/BrightSaturaContrastTest/BrightSaturaContrastUniform/BrightSaturaContrastUniform');
require('./assets/shaderScene/CaptureTest/CaptureTest');
require('./assets/shaderScene/CaptureTest/EncodeJPG');
require('./assets/shaderScene/LiquidBox2dTest/LiquidBox2dTest');
require('./assets/shaderScene/MeshPolygonSpriteTest/MeshPolygonSprite');
require('./assets/shaderScene/common/GTAssembler2D');
require('./assets/shaderScene/common/GTSimpleSpriteAssembler2D');
require('./assets/shaderScene/dissolveTest/DissolveTest');
require('./assets/shaderScene/sprite2dLight/Sprite2dLightTest');
